/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order"
  DROP COLUMN "currency";

UPDATE "schema_version"
  SET "migration" = FALSE
  WHERE "name" = '';

