/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_cart" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "uid" BIGINT NOT NULL,
  "merchant_id" BIGINT NOT NULL,
  "goods_id" TEXT NOT NULL,
  "count" BIGINT NOT NULL,
  "created_at" TIMESTAMP NULL,
  "updated_at" TIMESTAMP NULL);

CREATE INDEX "cmall_cart_uid_i"
  ON "cmall_cart" ("uid");

UPDATE "schema_version"
  SET "version" = 8, "migration" = TRUE
  WHERE "name" = '';

