/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order_bought_goods"
  ALTER COLUMN "value_merchant_id" SET NOT NULL,
  ALTER COLUMN "value_goods_id" SET NOT NULL,
  DROP COLUMN "value_owner";

UPDATE "schema_version"
  SET "migration" = FALSE
  WHERE "name" = '';

