/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order_bought_goods"
  ADD COLUMN "value_merchant_id" BIGINT NULL,
  ADD COLUMN "value_goods_id" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 7, "migration" = TRUE
  WHERE "name" = '';

