/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_cart"
  ADD COLUMN "selection" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 37, "migration" = TRUE
  WHERE "name" = '';

