/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "administrators"
  ADD COLUMN "gitea_token" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 23, "migration" = TRUE
  WHERE "name" = '';

