/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_order_kuaidi" (
  "object_id" BIGINT NOT NULL,
  "kuaidihao" BIGINT NOT NULL,
  "value_kuaidihao" TEXT NOT NULL,
  "value_kuaidigongsi" TEXT NOT NULL);

CREATE INDEX "cmall_order_kuaidi_object_id_i"
  ON "cmall_order_kuaidi" ("object_id");

CREATE INDEX "cmall_order_kuaidi_kuaidihao_i"
  ON "cmall_order_kuaidi" ("kuaidihao");

ALTER TABLE "cmall_order_kuaidi"
  ADD CONSTRAINT "object_id_fk"
    FOREIGN KEY ("object_id")
    REFERENCES "cmall_order" ("id")
    ON DELETE CASCADE;

UPDATE "schema_version"
  SET "version" = 17, "migration" = TRUE
  WHERE "name" = '';

