/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_index_page_goods" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "merchant_id" BIGINT NOT NULL,
  "goods" TEXT NOT NULL,
  "order" INTEGER NOT NULL);

UPDATE "schema_version"
  SET "version" = 26, "migration" = TRUE
  WHERE "name" = '';

