/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order"
  ADD COLUMN "seller" BIGINT NOT NULL DEFAULT 1;

CREATE INDEX "cmall_order_seller_i"
  ON "cmall_order" ("seller");

UPDATE "schema_version"
  SET "version" = 12, "migration" = TRUE
  WHERE "name" = '';

