/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_apply_for_mechant"
  ADD COLUMN "seq" BIGINT NULL;

CREATE INDEX "cmall_apply_for_mechant_seq_i"
  ON "cmall_apply_for_mechant" ("seq");

UPDATE "schema_version"
  SET "version" = 22, "migration" = TRUE
  WHERE "name" = '';

