/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_session"
  ADD COLUMN "ip_address" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 34, "migration" = TRUE
  WHERE "name" = '';

