/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_merchant"
  ADD COLUMN "gitea_password" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 14, "migration" = TRUE
  WHERE "name" = '';

