/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_apply_for_mechant"
  ADD COLUMN "state" SMALLINT NOT NULL DEFAULT 0;

UPDATE "schema_version"
  SET "version" = 21, "migration" = TRUE
  WHERE "name" = '';

