/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_session"
  ADD COLUMN "uid" BIGINT NULL;

UPDATE "schema_version"
  SET "version" = 35, "migration" = TRUE
  WHERE "name" = '';

