/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order"
  ADD COLUMN "snap_git_version" TEXT NOT NULL DEFAULT '';

CREATE INDEX "cmall_order_snap_git_version_i"
  ON "cmall_order" ("snap_git_version");

UPDATE "schema_version"
  SET "version" = 13, "migration" = TRUE
  WHERE "name" = '';

