/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP INDEX "cmall_session_owner_i";

ALTER TABLE "cmall_session"
  DROP COLUMN "owner";

UPDATE "schema_version"
  SET "migration" = FALSE
  WHERE "name" = '';

