/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_config"
  ADD COLUMN "config_name" TEXT NULL,
  ADD COLUMN "config_value" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 28, "migration" = TRUE
  WHERE "name" = '';

