/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_apply_for_mechant"
  DROP COLUMN "approved";

UPDATE "schema_version"
  SET "migration" = FALSE
  WHERE "name" = '';

