/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_wx_fenzhang" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "type" TEXT NOT NULL,
  "account" TEXT NOT NULL,
  "name" TEXT NOT NULL,
  "relation_type" TEXT NOT NULL,
  "percent" TEXT NOT NULL);

UPDATE "schema_version"
  SET "version" = 31, "migration" = TRUE
  WHERE "name" = '';

