/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_apply_for_mechant" (
  "id" BIGSERIAL NOT NULL PRIMARY KEY,
  "applicant" BIGINT NULL,
  "ext" TEXT NOT NULL,
  "created_at" TIMESTAMP NULL,
  "updated_at" TIMESTAMP NULL,
  "deleted_at" TIMESTAMP NULL);

CREATE INDEX "cmall_apply_for_mechant_applicant_i"
  ON "cmall_apply_for_mechant" ("applicant");

ALTER TABLE "cmall_apply_for_mechant"
  ADD CONSTRAINT "applicant_fk"
    FOREIGN KEY ("applicant")
    REFERENCES "cmall_user" ("uid")
    INITIALLY DEFERRED;

UPDATE "schema_version"
  SET "version" = 9, "migration" = TRUE
  WHERE "name" = '';

