/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_config"
  ALTER COLUMN "config_name" SET NOT NULL,
  ALTER COLUMN "config_value" SET NOT NULL;

UPDATE "schema_version"
  SET "migration" = FALSE
  WHERE "name" = '';

