/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_merchant"
  ADD COLUMN "exinfo_wx_mchid" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 27, "migration" = TRUE
  WHERE "name" = '';

