/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_session" (
  "cache_key" TEXT NOT NULL PRIMARY KEY,
  "owner" BIGINT NULL,
  "cache_content" TEXT NOT NULL,
  "created_at" TIMESTAMP NULL DEFAULT 'now()',
  "updated_at" TIMESTAMP NULL);

CREATE INDEX "cmall_session_owner_i"
  ON "cmall_session" ("owner");

CREATE INDEX "cmall_session_updated_at_i"
  ON "cmall_session" ("updated_at");

ALTER TABLE "cmall_session"
  ADD CONSTRAINT "owner_fk"
    FOREIGN KEY ("owner")
    REFERENCES "cmall_user" ("uid")
    INITIALLY DEFERRED;

UPDATE "schema_version"
  SET "version" = 32, "migration" = TRUE
  WHERE "name" = '';

