/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_3rd_public_kv_store" (
  "uid" BIGINT NOT NULL,
  "key_value" TEXT NOT NULL,
  "value" TEXT NOT NULL,
  PRIMARY KEY ("uid",
               "key_value"));

UPDATE "schema_version"
  SET "version" = 24, "migration" = TRUE
  WHERE "name" = '';

