/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order_bought_goods"
  ADD COLUMN "value_selection" TEXT NULL;

UPDATE "schema_version"
  SET "version" = 36, "migration" = TRUE
  WHERE "name" = '';

