/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_order"
  ADD COLUMN "kuaidifei" numeric NOT NULL DEFAULT '0';

UPDATE "schema_version"
  SET "version" = 30, "migration" = TRUE
  WHERE "name" = '';

