/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "cmall_apptoken" (
  "apptoken" TEXT NOT NULL PRIMARY KEY,
  "uid" BIGINT NOT NULL);

CREATE INDEX "cmall_apptoken_uid_i"
  ON "cmall_apptoken" ("uid");

UPDATE "schema_version"
  SET "version" = 18, "migration" = TRUE
  WHERE "name" = '';

