/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

ALTER TABLE "cmall_session"
  DROP CONSTRAINT "owner_fk";

UPDATE "schema_version"
  SET "version" = 33, "migration" = TRUE
  WHERE "name" = '';

