/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE TABLE "administrators" (
  "uid" BIGSERIAL NOT NULL PRIMARY KEY,
  "user" BIGINT NULL);

ALTER TABLE "administrators"
  ADD CONSTRAINT "user_fk"
    FOREIGN KEY ("user")
    REFERENCES "cmall_user" ("uid")
    INITIALLY DEFERRED;

UPDATE "schema_version"
  SET "version" = 10, "migration" = TRUE
  WHERE "name" = '';

