/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

CREATE UNIQUE INDEX "unique seq_applicant_id"
  ON "cmall_apply_for_mechant" (
    "applicant",
    "seq");

UPDATE "schema_version"
  SET "migration" = FALSE
  WHERE "name" = '';

