// -*- C++ -*-
//
// This file was generated by ODB, object-relational mapping (ORM)
// compiler for C++.
//

#ifndef DB_ODB_HXX
#define DB_ODB_HXX

// Begin prologue.
//
#include <odb/boost/version.hxx>
#if ODB_BOOST_VERSION != 2046900 // 2.5.0-b.19
#  error ODB and C++ compilers see different libodb-boost interface versions
#endif
#include <boost/shared_ptr.hpp>
#include <odb/boost/smart-ptr/pointer-traits.hxx>
#include <odb/boost/smart-ptr/wrapper-traits.hxx>
#include <odb/boost/optional/wrapper-traits.hxx>
#include <odb/boost/unordered/container-traits.hxx>
#include <odb/boost/date-time/pgsql/gregorian-traits.hxx>
#include <odb/boost/date-time/pgsql/posix-time-traits.hxx>
#include <odb/boost/multi-index/container-traits.hxx>
#include <odb/boost/uuid/pgsql/uuid-traits.hxx>
#include "db_traits.hpp"
//
// End prologue.

#include <odb/version.hxx>

#if (ODB_VERSION != 20469UL)
#error ODB runtime version mismatch
#endif

#include <odb/pre.hxx>

#include "cmall/db.hpp"

#include <memory>
#include <cstddef>
#include <utility>

#include <odb/core.hxx>
#include <odb/traits.hxx>
#include <odb/callback.hxx>
#include <odb/wrapper-traits.hxx>
#include <odb/pointer-traits.hxx>
#include <odb/container-traits.hxx>
#include <odb/no-op-cache-traits.hxx>
#include <odb/result.hxx>
#include <odb/simple-object-result.hxx>

#include <odb/details/unused.hxx>
#include <odb/details/shared-ptr.hxx>

namespace odb
{
  // cmall_config
  //
  template <>
  struct class_traits< ::cmall_config >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::cmall_config >
  {
    public:
    typedef ::cmall_config object_type;
    typedef ::boost::shared_ptr< ::cmall_config > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // cmall_user
  //
  template <>
  struct class_traits< ::cmall_user >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::cmall_user >
  {
    public:
    typedef ::cmall_user object_type;
    typedef ::std::shared_ptr< ::cmall_user > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // administrators
  //
  template <>
  struct class_traits< ::administrators >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::administrators >
  {
    public:
    typedef ::administrators object_type;
    typedef ::boost::shared_ptr< ::administrators > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // cmall_merchant
  //
  template <>
  struct class_traits< ::cmall_merchant >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::cmall_merchant >
  {
    public:
    typedef ::cmall_merchant object_type;
    typedef ::boost::shared_ptr< ::cmall_merchant > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = false;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // cmall_order
  //
  template <>
  struct class_traits< ::cmall_order >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::cmall_order >
  {
    public:
    typedef ::cmall_order object_type;
    typedef ::boost::shared_ptr< ::cmall_order > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // cmall_cart
  //
  template <>
  struct class_traits< ::cmall_cart >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::cmall_cart >
  {
    public:
    typedef ::cmall_cart object_type;
    typedef ::boost::shared_ptr< ::cmall_cart > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };

  // cmall_apply_for_mechant
  //
  template <>
  struct class_traits< ::cmall_apply_for_mechant >
  {
    static const class_kind kind = class_object;
  };

  template <>
  class access::object_traits< ::cmall_apply_for_mechant >
  {
    public:
    typedef ::cmall_apply_for_mechant object_type;
    typedef ::boost::shared_ptr< ::cmall_apply_for_mechant > pointer_type;
    typedef odb::pointer_traits<pointer_type> pointer_traits;

    static const bool polymorphic = false;

    typedef ::uint64_t id_type;

    static const bool auto_id = true;

    static const bool abstract = false;

    static id_type
    id (const object_type&);

    typedef
    no_op_pointer_cache_traits<pointer_type>
    pointer_cache_traits;

    typedef
    no_op_reference_cache_traits<object_type>
    reference_cache_traits;

    static void
    callback (database&, object_type&, callback_event);

    static void
    callback (database&, const object_type&, callback_event);
  };
}

#include <odb/details/buffer.hxx>

#include <odb/pgsql/version.hxx>
#include <odb/pgsql/forward.hxx>
#include <odb/pgsql/binding.hxx>
#include <odb/pgsql/pgsql-types.hxx>
#include <odb/pgsql/query.hxx>

namespace odb
{
  // cmall_config
  //
  template <typename A>
  struct query_columns< ::cmall_config, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;
  };

  template <typename A>
  const typename query_columns< ::cmall_config, id_pgsql, A >::id_type_
  query_columns< ::cmall_config, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  struct pointer_query_columns< ::cmall_config, id_pgsql, A >:
    query_columns< ::cmall_config, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::cmall_config, id_pgsql >:
    public access::object_traits< ::cmall_config >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 1UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::cmall_config, id_common >:
    public access::object_traits_impl< ::cmall_config, id_pgsql >
  {
  };

  // Recipient
  //
  template <>
  class access::composite_value_traits< ::Recipient, id_pgsql >
  {
    public:
    typedef ::Recipient value_type;

    struct image_type
    {
      // name
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // telephone
      //
      details::buffer telephone_value;
      std::size_t telephone_size;
      bool telephone_null;

      // address
      //
      details::buffer address_value;
      std::size_t address_size;
      bool address_null;

      // province
      //
      details::buffer province_value;
      std::size_t province_size;
      bool province_null;

      // city
      //
      details::buffer city_value;
      std::size_t city_size;
      bool city_null;

      // district
      //
      details::buffer district_value;
      std::size_t district_size;
      bool district_null;

      // specific_address
      //
      details::buffer specific_address_value;
      std::size_t specific_address_size;
      bool specific_address_null;

      // as_default
      //
      bool as_default_value;
      bool as_default_null;
    };

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static bool
    init (image_type&,
          const value_type&,
          pgsql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              pgsql::statement_kind);

    static const std::size_t column_count = 8UL;
  };

  // cmall_user
  //
  template <typename A>
  struct query_columns< ::cmall_user, id_pgsql, A >
  {
    // uid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    uid_type_;

    static const uid_type_ uid;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;

    // active_phone
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    active_phone_type_;

    static const active_phone_type_ active_phone;

    // verified
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    verified_type_;

    static const verified_type_ verified;

    // state
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint8_t,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    state_type_;

    static const state_type_ state;

    // desc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    desc_type_;

    static const desc_type_ desc;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // deleted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    deleted_at_type_;

    static const deleted_at_type_ deleted_at;
  };

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::uid_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  uid (A::table_name, "\"uid\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::name_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::active_phone_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  active_phone (A::table_name, "\"active_phone\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::verified_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  verified (A::table_name, "\"verified\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::state_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  state (A::table_name, "\"state\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::desc_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  desc (A::table_name, "\"desc\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::created_at_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::updated_at_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_user, id_pgsql, A >::deleted_at_type_
  query_columns< ::cmall_user, id_pgsql, A >::
  deleted_at (A::table_name, "\"deleted_at\"", 0);

  template <typename A>
  struct pointer_query_columns< ::cmall_user, id_pgsql, A >:
    query_columns< ::cmall_user, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::cmall_user, id_pgsql >:
    public access::object_traits< ::cmall_user >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // uid_
      //
      long long uid_value;
      bool uid_null;

      // name_
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // active_phone
      //
      details::buffer active_phone_value;
      std::size_t active_phone_size;
      bool active_phone_null;

      // verified_
      //
      bool verified_value;
      bool verified_null;

      // state_
      //
      short state_value;
      bool state_null;

      // desc_
      //
      details::buffer desc_value;
      std::size_t desc_size;
      bool desc_null;

      // created_at_
      //
      long long created_at_value;
      bool created_at_null;

      // updated_at_
      //
      long long updated_at_value;
      bool updated_at_null;

      // deleted_at_
      //
      long long deleted_at_value;
      bool deleted_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // used_phones
    //
    struct used_phones_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 3UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::std::basic_string< char > > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< used_phones_traits > statements_type;

      struct data_image_type
      {
        // index
        //
        long long index_value;
        bool index_null;

        // value
        //
        details::buffer value_value;
        std::size_t value_size;
        bool value_null;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (data_image_type&,
            index_type*,
            const value_type&);

      static void
      init (index_type&,
            value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      persist (const container_type&,
               statements_type&);

      static void
      load (container_type&,
            statements_type&);

      static void
      update (const container_type&,
              statements_type&);

      static void
      erase (statements_type&);
    };

    // recipients
    //
    struct recipients_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 10UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::Recipient > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< recipients_traits > statements_type;

      struct data_image_type
      {
        // index
        //
        long long index_value;
        bool index_null;

        // value
        //
        composite_value_traits< value_type, id_pgsql >::image_type value_value;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (data_image_type&,
            index_type*,
            const value_type&);

      static void
      init (index_type&,
            value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      persist (const container_type&,
               statements_type&);

      static void
      load (container_type&,
            statements_type&);

      static void
      update (const container_type&,
              statements_type&);

      static void
      erase (statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 9UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::cmall_user, id_common >:
    public access::object_traits_impl< ::cmall_user, id_pgsql >
  {
  };

  // administrators
  //
  template <typename A>
  struct pointer_query_columns< ::administrators, id_pgsql, A >
  {
    // uid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    uid_type_;

    static const uid_type_ uid;

    // user
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    user_type_;

    static const user_type_ user;
  };

  template <typename A>
  const typename pointer_query_columns< ::administrators, id_pgsql, A >::uid_type_
  pointer_query_columns< ::administrators, id_pgsql, A >::
  uid (A::table_name, "\"uid\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::administrators, id_pgsql, A >::user_type_
  pointer_query_columns< ::administrators, id_pgsql, A >::
  user (A::table_name, "\"user\"", 0);

  template <>
  class access::object_traits_impl< ::administrators, id_pgsql >:
    public access::object_traits< ::administrators >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // uid_
      //
      long long uid_value;
      bool uid_null;

      // user
      //
      long long user_value;
      bool user_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct user_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 2UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::administrators, id_common >:
    public access::object_traits_impl< ::administrators, id_pgsql >
  {
  };

  // cmall_merchant
  //
  template <typename A>
  struct query_columns< ::cmall_merchant, id_pgsql, A >
  {
    // uid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    uid_type_;

    static const uid_type_ uid;

    // name
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    name_type_;

    static const name_type_ name;

    // verified
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        bool,
        pgsql::id_boolean >::query_type,
      pgsql::id_boolean >
    verified_type_;

    static const verified_type_ verified;

    // state
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint8_t,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    state_type_;

    static const state_type_ state;

    // desc
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    desc_type_;

    static const desc_type_ desc;

    // api_token
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    api_token_type_;

    static const api_token_type_ api_token;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // deleted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    deleted_at_type_;

    static const deleted_at_type_ deleted_at;

    // repo_path
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    repo_path_type_;

    static const repo_path_type_ repo_path;
  };

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::uid_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  uid (A::table_name, "\"uid\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::name_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  name (A::table_name, "\"name\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::verified_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  verified (A::table_name, "\"verified\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::state_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  state (A::table_name, "\"state\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::desc_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  desc (A::table_name, "\"desc\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::api_token_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  api_token (A::table_name, "\"api_token\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::created_at_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::updated_at_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::deleted_at_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  deleted_at (A::table_name, "\"deleted_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_merchant, id_pgsql, A >::repo_path_type_
  query_columns< ::cmall_merchant, id_pgsql, A >::
  repo_path (A::table_name, "\"repo_path\"", 0);

  template <typename A>
  struct pointer_query_columns< ::cmall_merchant, id_pgsql, A >:
    query_columns< ::cmall_merchant, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::cmall_merchant, id_pgsql >:
    public access::object_traits< ::cmall_merchant >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // uid_
      //
      long long uid_value;
      bool uid_null;

      // name_
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // verified_
      //
      bool verified_value;
      bool verified_null;

      // state_
      //
      short state_value;
      bool state_null;

      // desc_
      //
      details::buffer desc_value;
      std::size_t desc_size;
      bool desc_null;

      // api_token_
      //
      details::buffer api_token_value;
      std::size_t api_token_size;
      bool api_token_null;

      // created_at_
      //
      long long created_at_value;
      bool created_at_null;

      // updated_at_
      //
      long long updated_at_value;
      bool updated_at_null;

      // deleted_at_
      //
      long long deleted_at_value;
      bool deleted_at_null;

      // repo_path
      //
      details::buffer repo_path_value;
      std::size_t repo_path_size;
      bool repo_path_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 10UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, const object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::cmall_merchant, id_common >:
    public access::object_traits_impl< ::cmall_merchant, id_pgsql >
  {
  };

  // goods_snapshot
  //
  template <>
  class access::composite_value_traits< ::goods_snapshot, id_pgsql >
  {
    public:
    typedef ::goods_snapshot value_type;

    struct image_type
    {
      // merchant_id
      //
      long long merchant_id_value;
      bool merchant_id_null;

      // goods_id
      //
      details::buffer goods_id_value;
      std::size_t goods_id_size;
      bool goods_id_null;

      // name_
      //
      details::buffer name_value;
      std::size_t name_size;
      bool name_null;

      // price_
      //
      details::buffer price_value;
      std::size_t price_size;
      bool price_null;

      // description_
      //
      details::buffer description_value;
      std::size_t description_size;
      bool description_null;

      // good_version_git
      //
      details::buffer good_version_git_value;
      std::size_t good_version_git_size;
      bool good_version_git_null;
    };

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static bool
    init (image_type&,
          const value_type&,
          pgsql::statement_kind);

    static void
    init (value_type&,
          const image_type&,
          database*);

    static bool
    get_null (const image_type&);

    static void
    set_null (image_type&,
              pgsql::statement_kind);

    static const std::size_t column_count = 6UL;
  };

  // cmall_order
  //
  template <typename A>
  struct query_columns< ::cmall_order, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // oid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    oid_type_;

    static const oid_type_ oid;

    // buyer
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    buyer_type_;

    static const buyer_type_ buyer;

    // seller
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    seller_type_;

    static const seller_type_ seller;

    // price
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::cpp_numeric,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    price_type_;

    static const price_type_ price;

    // currency_rate
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::cpp_numeric,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    currency_rate_type_;

    static const currency_rate_type_ currency_rate;

    // pay_amount
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::cpp_numeric,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    pay_amount_type_;

    static const pay_amount_type_ pay_amount;

    // stage
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint8_t,
        pgsql::id_smallint >::query_type,
      pgsql::id_smallint >
    stage_type_;

    static const stage_type_ stage;

    // payed_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    payed_at_type_;

    static const payed_at_type_ payed_at;

    // close_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    close_at_type_;

    static const close_at_type_ close_at;

    // ext
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::basic_string< char >,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    ext_type_;

    static const ext_type_ ext;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // deleted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    deleted_at_type_;

    static const deleted_at_type_ deleted_at;
  };

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::id_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::oid_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  oid (A::table_name, "\"oid\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::buyer_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  buyer (A::table_name, "\"buyer\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::seller_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  seller (A::table_name, "\"seller\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::price_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  price (A::table_name, "\"price\"", "(?)::numeric");

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::currency_rate_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  currency_rate (A::table_name, "\"currency_rate\"", "(?)::numeric");

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::pay_amount_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  pay_amount (A::table_name, "\"pay_amount\"", "(?)::numeric");

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::stage_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  stage (A::table_name, "\"stage\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::payed_at_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  payed_at (A::table_name, "\"payed_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::close_at_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  close_at (A::table_name, "\"close_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::ext_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  ext (A::table_name, "\"ext\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::created_at_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::updated_at_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_order, id_pgsql, A >::deleted_at_type_
  query_columns< ::cmall_order, id_pgsql, A >::
  deleted_at (A::table_name, "\"deleted_at\"", 0);

  template <typename A>
  struct pointer_query_columns< ::cmall_order, id_pgsql, A >:
    query_columns< ::cmall_order, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::cmall_order, id_pgsql >:
    public access::object_traits< ::cmall_order >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // oid_
      //
      details::buffer oid_value;
      std::size_t oid_size;
      bool oid_null;

      // buyer_
      //
      long long buyer_value;
      bool buyer_null;

      // seller_
      //
      long long seller_value;
      bool seller_null;

      // price_
      //
      details::buffer price_value;
      std::size_t price_size;
      bool price_null;

      // currency_rate_
      //
      details::buffer currency_rate_value;
      std::size_t currency_rate_size;
      bool currency_rate_null;

      // pay_amount_
      //
      details::buffer pay_amount_value;
      std::size_t pay_amount_size;
      bool pay_amount_null;

      // stage_
      //
      short stage_value;
      bool stage_null;

      // payed_at_
      //
      long long payed_at_value;
      bool payed_at_null;

      // close_at_
      //
      long long close_at_value;
      bool close_at_null;

      // ext_
      //
      details::buffer ext_value;
      std::size_t ext_size;
      bool ext_null;

      // created_at_
      //
      long long created_at_value;
      bool created_at_null;

      // updated_at_
      //
      long long updated_at_value;
      bool updated_at_null;

      // deleted_at_
      //
      long long deleted_at_value;
      bool deleted_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    // recipient
    //
    struct recipient_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 10UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::Recipient > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< recipient_traits > statements_type;

      struct data_image_type
      {
        // index
        //
        long long index_value;
        bool index_null;

        // value
        //
        composite_value_traits< value_type, id_pgsql >::image_type value_value;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (data_image_type&,
            index_type*,
            const value_type&);

      static void
      init (index_type&,
            value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      persist (const container_type&,
               statements_type&);

      static void
      load (container_type&,
            statements_type&);

      static void
      update (const container_type&,
              statements_type&);

      static void
      erase (statements_type&);
    };

    // bought_goods
    //
    struct bought_goods_traits
    {
      static const char select_name[];
      static const char insert_name[];
      static const char delete_name[];

      static const unsigned int insert_types[];

      static const std::size_t id_column_count = 1UL;
      static const std::size_t data_column_count = 8UL;

      static const bool versioned = false;

      static const char insert_statement[];
      static const char select_statement[];
      static const char delete_statement[];

      typedef ::std::vector< ::goods_snapshot > container_type;
      typedef
      odb::access::container_traits<container_type>
      container_traits_type;
      typedef container_traits_type::index_type index_type;
      typedef container_traits_type::value_type value_type;

      typedef ordered_functions<index_type, value_type> functions_type;
      typedef pgsql::container_statements< bought_goods_traits > statements_type;

      struct data_image_type
      {
        // index
        //
        long long index_value;
        bool index_null;

        // value
        //
        composite_value_traits< value_type, id_pgsql >::image_type value_value;

        std::size_t version;
      };

      static void
      bind (pgsql::bind*,
            const pgsql::bind* id,
            std::size_t id_size,
            data_image_type&);

      static void
      grow (data_image_type&,
            bool*);

      static void
      init (data_image_type&,
            index_type*,
            const value_type&);

      static void
      init (index_type&,
            value_type&,
            const data_image_type&,
            database*);

      static void
      insert (index_type, const value_type&, void*);

      static bool
      select (index_type&, value_type&, void*);

      static void
      delete_ (void*);

      static void
      persist (const container_type&,
               statements_type&);

      static void
      load (container_type&,
            statements_type&);

      static void
      update (const container_type&,
              statements_type&);

      static void
      erase (statements_type&);
    };

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 14UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::cmall_order, id_common >:
    public access::object_traits_impl< ::cmall_order, id_pgsql >
  {
  };

  // cmall_cart
  //
  template <typename A>
  struct query_columns< ::cmall_cart, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // uid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    uid_type_;

    static const uid_type_ uid;

    // merchant_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    merchant_id_type_;

    static const merchant_id_type_ merchant_id;

    // goods_id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    goods_id_type_;

    static const goods_id_type_ goods_id;

    // count
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    count_type_;

    static const count_type_ count;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;
  };

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::id_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::uid_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  uid (A::table_name, "\"uid\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::merchant_id_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  merchant_id (A::table_name, "\"merchant_id\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::goods_id_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  goods_id (A::table_name, "\"goods_id\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::count_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  count (A::table_name, "\"count\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::created_at_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_cart, id_pgsql, A >::updated_at_type_
  query_columns< ::cmall_cart, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  struct pointer_query_columns< ::cmall_cart, id_pgsql, A >:
    query_columns< ::cmall_cart, id_pgsql, A >
  {
  };

  template <>
  class access::object_traits_impl< ::cmall_cart, id_pgsql >:
    public access::object_traits< ::cmall_cart >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // uid_
      //
      long long uid_value;
      bool uid_null;

      // merchant_id_
      //
      long long merchant_id_value;
      bool merchant_id_null;

      // goods_id_
      //
      details::buffer goods_id_value;
      std::size_t goods_id_size;
      bool goods_id_null;

      // count_
      //
      long long count_value;
      bool count_null;

      // created_at_
      //
      long long created_at_value;
      bool created_at_null;

      // updated_at_
      //
      long long updated_at_value;
      bool updated_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 7UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::cmall_cart, id_common >:
    public access::object_traits_impl< ::cmall_cart, id_pgsql >
  {
  };

  // cmall_apply_for_mechant
  //
  template <typename A>
  struct pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // applicant
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    applicant_type_;

    static const applicant_type_ applicant;

    // ext
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    ext_type_;

    static const ext_type_ ext;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // deleted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    deleted_at_type_;

    static const deleted_at_type_ deleted_at;
  };

  template <typename A>
  const typename pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::id_type_
  pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::applicant_type_
  pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  applicant (A::table_name, "\"applicant\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::ext_type_
  pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  ext (A::table_name, "\"ext\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::created_at_type_
  pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::updated_at_type_
  pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  const typename pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::deleted_at_type_
  pointer_query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  deleted_at (A::table_name, "\"deleted_at\"", 0);

  template <>
  class access::object_traits_impl< ::cmall_apply_for_mechant, id_pgsql >:
    public access::object_traits< ::cmall_apply_for_mechant >
  {
    public:
    struct id_image_type
    {
      long long id_value;
      bool id_null;

      std::size_t version;
    };

    struct image_type
    {
      // id_
      //
      long long id_value;
      bool id_null;

      // applicant_
      //
      long long applicant_value;
      bool applicant_null;

      // ext_
      //
      details::buffer ext_value;
      std::size_t ext_size;
      bool ext_null;

      // created_at_
      //
      long long created_at_value;
      bool created_at_null;

      // updated_at_
      //
      long long updated_at_value;
      bool updated_at_null;

      // deleted_at_
      //
      long long deleted_at_value;
      bool deleted_at_null;

      std::size_t version;
    };

    struct extra_statement_cache_type;

    struct applicant_tag;

    using object_traits<object_type>::id;

    static id_type
    id (const id_image_type&);

    static id_type
    id (const image_type&);

    static bool
    grow (image_type&,
          bool*);

    static void
    bind (pgsql::bind*,
          image_type&,
          pgsql::statement_kind);

    static void
    bind (pgsql::bind*, id_image_type&);

    static bool
    init (image_type&,
          const object_type&,
          pgsql::statement_kind);

    static void
    init (object_type&,
          const image_type&,
          database*);

    static void
    init (id_image_type&, const id_type&);

    typedef pgsql::object_statements<object_type> statements_type;

    typedef pgsql::query_base query_base_type;

    static const std::size_t column_count = 6UL;
    static const std::size_t id_column_count = 1UL;
    static const std::size_t inverse_column_count = 0UL;
    static const std::size_t readonly_column_count = 0UL;
    static const std::size_t managed_optimistic_column_count = 0UL;

    static const std::size_t separate_load_column_count = 0UL;
    static const std::size_t separate_update_column_count = 0UL;

    static const bool versioned = false;

    static const char persist_statement[];
    static const char find_statement[];
    static const char update_statement[];
    static const char erase_statement[];
    static const char query_statement[];
    static const char erase_query_statement[];

    static const char table_name[];

    static void
    persist (database&, object_type&);

    static pointer_type
    find (database&, const id_type&);

    static bool
    find (database&, const id_type&, object_type&);

    static bool
    reload (database&, object_type&);

    static void
    update (database&, const object_type&);

    static void
    erase (database&, const id_type&);

    static void
    erase (database&, const object_type&);

    static result<object_type>
    query (database&, const query_base_type&);

    static unsigned long long
    erase_query (database&, const query_base_type&);

    static const char persist_statement_name[];
    static const char find_statement_name[];
    static const char update_statement_name[];
    static const char erase_statement_name[];
    static const char query_statement_name[];
    static const char erase_query_statement_name[];

    static const unsigned int persist_statement_types[];
    static const unsigned int find_statement_types[];
    static const unsigned int update_statement_types[];

    public:
    static bool
    find_ (statements_type&,
           const id_type*);

    static void
    load_ (statements_type&,
           object_type&,
           bool reload);
  };

  template <>
  class access::object_traits_impl< ::cmall_apply_for_mechant, id_common >:
    public access::object_traits_impl< ::cmall_apply_for_mechant, id_pgsql >
  {
  };

  // cmall_config
  //
  // cmall_user
  //
  // administrators
  //
  template <>
  struct alias_traits<
    ::cmall_user,
    id_pgsql,
    access::object_traits_impl< ::administrators, id_pgsql >::user_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::administrators, id_pgsql >
  {
    // user
    //
    typedef
    odb::alias_traits<
      ::cmall_user,
      id_pgsql,
      access::object_traits_impl< ::administrators, id_pgsql >::user_tag>
    user_alias_;
  };

  template <typename A>
  struct query_columns< ::administrators, id_pgsql, A >:
    query_columns_base< ::administrators, id_pgsql >
  {
    // uid
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    uid_type_;

    static const uid_type_ uid;

    // user
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    user_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::cmall_user,
        id_pgsql,
        user_alias_ > >
    user_pointer_type_;

    struct user_type_: user_pointer_type_, user_column_type_
    {
      user_type_ (const char* t, const char* c, const char* conv)
        : user_column_type_ (t, c, conv)
      {
      }
    };

    static const user_type_ user;
  };

  template <typename A>
  const typename query_columns< ::administrators, id_pgsql, A >::uid_type_
  query_columns< ::administrators, id_pgsql, A >::
  uid (A::table_name, "\"uid\"", 0);

  template <typename A>
  const typename query_columns< ::administrators, id_pgsql, A >::user_type_
  query_columns< ::administrators, id_pgsql, A >::
  user (A::table_name, "\"user\"", 0);

  // cmall_merchant
  //
  // cmall_order
  //
  // cmall_cart
  //
  // cmall_apply_for_mechant
  //
  template <>
  struct alias_traits<
    ::cmall_user,
    id_pgsql,
    access::object_traits_impl< ::cmall_apply_for_mechant, id_pgsql >::applicant_tag>
  {
    static const char table_name[];
  };

  template <>
  struct query_columns_base< ::cmall_apply_for_mechant, id_pgsql >
  {
    // applicant
    //
    typedef
    odb::alias_traits<
      ::cmall_user,
      id_pgsql,
      access::object_traits_impl< ::cmall_apply_for_mechant, id_pgsql >::applicant_tag>
    applicant_alias_;
  };

  template <typename A>
  struct query_columns< ::cmall_apply_for_mechant, id_pgsql, A >:
    query_columns_base< ::cmall_apply_for_mechant, id_pgsql >
  {
    // id
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    id_type_;

    static const id_type_ id;

    // applicant
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::uint64_t,
        pgsql::id_bigint >::query_type,
      pgsql::id_bigint >
    applicant_column_type_;

    typedef
    odb::query_pointer<
      odb::pointer_query_columns<
        ::cmall_user,
        id_pgsql,
        applicant_alias_ > >
    applicant_pointer_type_;

    struct applicant_type_: applicant_pointer_type_, applicant_column_type_
    {
      applicant_type_ (const char* t, const char* c, const char* conv)
        : applicant_column_type_ (t, c, conv)
      {
      }
    };

    static const applicant_type_ applicant;

    // ext
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::std::string,
        pgsql::id_string >::query_type,
      pgsql::id_string >
    ext_type_;

    static const ext_type_ ext;

    // created_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    created_at_type_;

    static const created_at_type_ created_at;

    // updated_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    updated_at_type_;

    static const updated_at_type_ updated_at;

    // deleted_at
    //
    typedef
    pgsql::query_column<
      pgsql::value_traits<
        ::boost::posix_time::ptime,
        pgsql::id_timestamp >::query_type,
      pgsql::id_timestamp >
    deleted_at_type_;

    static const deleted_at_type_ deleted_at;
  };

  template <typename A>
  const typename query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::id_type_
  query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  id (A::table_name, "\"id\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::applicant_type_
  query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  applicant (A::table_name, "\"applicant\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::ext_type_
  query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  ext (A::table_name, "\"ext\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::created_at_type_
  query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  created_at (A::table_name, "\"created_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::updated_at_type_
  query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  updated_at (A::table_name, "\"updated_at\"", 0);

  template <typename A>
  const typename query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::deleted_at_type_
  query_columns< ::cmall_apply_for_mechant, id_pgsql, A >::
  deleted_at (A::table_name, "\"deleted_at\"", 0);
}

#include "cmall/db-odb.ihh"

#include <odb/post.hxx>

#endif // DB_ODB_HXX
